heremaps/here-ios-sdk-examples

.ci/buildAll.sh
.ci/preInstall.sh
.gitignore
.travis.yml
geocoder-and-reverse-geocoder-ios/GeocoderRevGeocoderApp.xcodeproj/project.pbxproj
geocoder-and-reverse-geocoder-ios/GeocoderRevGeocoderApp.xcodeproj/xcshareddata/xcschemes/GeocoderRevGeocoderApp.xcscheme
map-attribute-ios/MapAttributeApp.xcodeproj/project.pbxproj
map-attribute-ios/MapAttributeApp.xcodeproj/xcshareddata/xcschemes/MapAttributeApp.xcscheme
map-customization-ios/MapCustomizationApp.xcodeproj/project.pbxproj
map-customization-ios/MapCustomizationApp.xcodeproj/xcshareddata/xcschemes/MapCustomizationApp.xcscheme
map-downloader-ios/MapDownloaderApp.xcodeproj/project.pbxproj
map-downloader-ios/MapDownloaderApp.xcodeproj/xcshareddata/xcschemes/MapDownloaderApp.xcscheme
map-gestures-ios/MapGesturesApp.xcodeproj/project.pbxproj
map-gestures-ios/MapGesturesApp.xcodeproj/xcshareddata/xcschemes/MapGesturesApp.xcscheme
map-objects-ios/MapObjectsApp.xcodeproj/project.pbxproj
map-objects-ios/MapObjectsApp.xcodeproj/xcshareddata/xcschemes/MapObjectsApp.xcscheme
map-raster-tile/MapRasterTiles.xcodeproj/project.pbxproj
map-raster-tile/MapRasterTiles.xcodeproj/xcshareddata/xcschemes/MapRasterTiles.xcscheme
map-rendering-ios/MapEngineinitializationApp.xcodeproj/project.pbxproj
map-rendering-ios/MapEngineinitializationApp.xcodeproj/xcshareddata/xcschemes/MapEngineinitializationApp.xcscheme
routing-ios/RoutingApp.xcodeproj/project.pbxproj
routing-ios/RoutingApp.xcodeproj/xcshareddata/xcschemes/RoutingApp.xcscheme
search-ios/SearchApp.xcodeproj/project.pbxproj
search-ios/SearchApp.xcodeproj/xcshareddata/xcschemes/SearchApp.xcscheme
turn-by-turn-navigation-ios/GuidanceApp.xcodeproj/project.pbxproj
turn-by-turn-navigation-ios/GuidanceApp.xcodeproj/xcshareddata/xcschemes/GuidanceApp.xcscheme

- Ignore NMAKit, user data and build folders
- Add dependency references for projects
- Share projects schemes for CI
- Add pre-installer and builder
- Add travis configuration file

Enabling Travis-CI

---

.github/SUPPORT

For the GitHub feature see
https://github.com/blog/2400-support-file-support

Add a SUPPORT file to direct non-commercial users to StackOverflow

---

.ci/buildAll.sh
.travis.yml

- With this commit Xcode and simulator version updated on Travis-Ci configuration.

Update Xcode and simulator version on CI

---

README.md
geocoder-and-reverse-geocoder-ios/Podfile
here-positioning-ios/Podfile
map-attribute-ios/Podfile
map-customization-ios/Podfile
map-downloader-ios/Podfile
map-gestures-ios/Podfile
map-objects-ios/Podfile
map-raster-tile/Podfile
map-rendering-ios/Podfile
routing-ios/Podfile
search-ios/Podfile
turn-by-turn-navigation-ios/Podfile

Updated pod files to use latest SDK version

Updated README.md, updated pod files versions

---

geocoder-and-reverse-geocoder-ios/Podfile
map-attribute-ios/Podfile
map-customization-ios/Podfile
map-downloader-ios/Podfile
map-gestures-ios/Podfile
map-objects-ios/Podfile
map-raster-tile/Podfile
map-rendering-ios/Podfile
routing-ios/Podfile
routing-ios/RoutingApp.xcodeproj/project.pbxproj
search-ios/Podfile
turn-by-turn-navigation-ios/Podfile

Muted smart quotes warning of CocoaPods

Fixed RoutingApp linker error.

---

geocoder-and-reverse-geocoder-ios-swift/GeocoderRevGeocoderApp/AppDelegate.swift
map-attribute-swift/MapAttributeApp.xcodeproj/project.pbxproj
map-attribute-swift/MapAttributeApp/AppDelegate.swift
map-attribute-swift/MapAttributeApp/Info.plist
map-customization-ios-swift/MapCustomizationApp/ViewController.swift
map-gestures-ios-swift/MapGesturesApp/ViewController.swift
map-gestures-ios/MapGesturesApp/MainViewController.m
map-objects-ios-swift/MapObjectsApp.xcodeproj/project.pbxproj
routing-ios-swift/RoutingApp/AppDelegate.swift
search-ios-swift/SearchApp.xcodeproj/project.pbxproj
search-ios-swift/SearchApp/AppDelegate.swift

* fixed map-customization-ios-swift app
* fixed map-gestures-ios, map-gestures-ios-swift apps
* resolved  "red" folder
* adopt to Swift 4.2

Fixed map-customization, map-gestures apps. Resolved minor issues.

---

README.md

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@here.com>

README: Apply some trivial formatting improvements

---

README.md
here-mobile-sdk-ui-kit-swift/.gitignore
here-mobile-sdk-ui-kit-swift/GuideMeToHERE.xcodeproj/project.pbxproj
here-mobile-sdk-ui-kit-swift/GuideMeToHERE/AppDelegate.swift
here-mobile-sdk-ui-kit-swift/GuideMeToHERE/Assets.xcassets/AppIcon.appiconset/Contents.json
here-mobile-sdk-ui-kit-swift/GuideMeToHERE/Assets.xcassets/Contents.json
here-mobile-sdk-ui-kit-swift/GuideMeToHERE/Base.lproj/LaunchScreen.storyboard
here-mobile-sdk-ui-kit-swift/GuideMeToHERE/Base.lproj/Main.storyboard
here-mobile-sdk-ui-kit-swift/GuideMeToHERE/Info.plist
here-mobile-sdk-ui-kit-swift/GuideMeToHERE/ViewController.swift
here-mobile-sdk-ui-kit-swift/Podfile
here-mobile-sdk-ui-kit-swift/Podfile.lock
here-mobile-sdk-ui-kit-swift/README.md

Add new Swift example to show how to build user interfaces
with the HERE MSDKUI 2.0 framework and the HERE Mobile SDK.

Add MSDKUI example

---

map-objects-ios/MapObjectsApp/Base.lproj/Main.storyboard
map-objects-ios/MapObjectsApp/MainViewController.m

Add sample that shows how to navigate to the set of geo coordinates.

---

map-objects-ios/MapObjectsApp/MainViewController.m

- Added code for iPad UIAlertController ActionSheet presentation without crash.
- Also made minor code changes to Objective C style

Fixed crash on iPad. Updated ENUM

---

here-positioning-ios/HEREPositioningApp/Base.lproj/Main.storyboard
here-positioning-ios/HEREPositioningApp/FcwTableViewCell.h
here-positioning-ios/HEREPositioningApp/FcwTableViewCell.m
here-positioning-ios/HEREPositioningApp/FcwTableViewCell.xib
here-positioning-ios/HEREPositioningApp/MainViewController.h
here-positioning-ios/HEREPositioningApp/MainViewController.m

Add routing & venues to positioning example app

Here Positioning Routing

---

here-positioning-ios/HEREPositioningApp.xcodeproj/project.pbxproj

Signed-off-by: Mikko Honkanen <mihonka@users.noreply.github.com>

HERE Positioning iOS example fix to project file

---

README.md
geocoder-and-reverse-geocoder-ios-swift/Podfile
geocoder-and-reverse-geocoder-ios/Podfile
here-positioning-ios-swift/Podfile
here-positioning-ios/Podfile
map-attribute-ios/Podfile
map-attribute-swift/Podfile
map-customization-ios-swift/Podfile
map-customization-ios/Podfile
map-downloader-ios-swift/Podfile
map-downloader-ios/Podfile
map-gestures-ios-swift/Podfile
map-gestures-ios/Podfile
map-objects-ios-swift/Podfile
map-objects-ios/Podfile
map-raster-tile-swift/Podfile
map-raster-tile/Podfile
map-rendering-ios-swift/Podfile
map-rendering-ios/Podfile
route-tta-ios-swift/Podfile
route-tta-ios/Podfile
routing-ios-swift/Podfile
routing-ios/Podfile
search-ios-swift/Podfile
search-ios/Podfile
turn-by-turn-navigation-ios-swift/Podfile
turn-by-turn-navigation-ios/Podfile

- Updated pod file in samples
- Updated README.md

Updated samples to use CocoaPods version 3.12

---

map-objects-ios-swift/MapObjectsApp/MainViewController.swift
map-objects-ios/MapObjectsApp/MainViewController.m

- Extended ObjC and Swift MapObject samples with example NMAMapMarker dragging usage

Added example of MapMarker draggable property usage

---

README.md
here-mobile-sdk-ui-kit-swift/GuideMeToHERE/ViewController.swift
here-mobile-sdk-ui-kit-swift/README.md
map-downloader-ios-swift/MapDownloaderApp/MapPackageTableViewController.swift
map-downloader-ios/MapDownloaderApp/MapPackageTableViewController.m
route-tta-ios-swift/RouteTTAApp/RouteUtil.swift
route-tta-ios/RouteTTAApp/ViewController.m
search-ios-swift/SearchApp/MainViewController.swift
search-ios-swift/SearchApp/PlaceDetailViewController.swift
search-ios-swift/SearchApp/ResultTableViewController.swift
search-ios/SearchApp/MainViewController.m
search-ios/SearchApp/PlaceDetailViewController.m
search-ios/SearchApp/ResultTableViewController.m
turn-by-turn-navigation-ios-swift/GuidanceApp/MainViewController.swift
turn-by-turn-navigation-ios/GuidanceApp/MainViewController.m

Use the official SDK name.

---

README.md
auto-suggest-ios-swift/Podfile
auto-suggest-ios/Podfile
geocoder-and-reverse-geocoder-ios-swift/Podfile
geocoder-and-reverse-geocoder-ios/Podfile
here-positioning-ios-swift/Podfile
here-positioning-ios/Podfile
map-attribute-ios-swift/Podfile
map-attribute-ios/Podfile
map-customization-ios-swift/Podfile
map-customization-ios/Podfile
map-downloader-ios-swift/Podfile
map-downloader-ios/Podfile
map-gestures-ios-swift/Podfile
map-gestures-ios/Podfile
map-objects-ios-swift/Podfile
map-objects-ios/Podfile
map-raster-tile-ios-swift/Podfile
map-raster-tile-ios/Podfile
map-rendering-ios-swift/Podfile
map-rendering-ios/Podfile
route-tta-ios-swift/Podfile
route-tta-ios/Podfile
routing-ios-swift/Podfile
routing-ios/Podfile
search-ios-swift/Podfile
search-ios/Podfile
turn-by-turn-navigation-ios-swift/Podfile
turn-by-turn-navigation-ios/Podfile

Signed-off-by: Mykola Farion <ext-mykola.farion@here.com>

Updated podfiles to use the latest mSDK version (3.15)

---

auto-suggest-ios-swift/AutoSuggestApp/AppDelegate.swift
auto-suggest-ios/AutoSuggestApp/AppDelegate.m
here-mobile-sdk-ui-kit-swift/GuideMeToHERE/AppDelegate.swift

Signed-off-by: Mykola Farion <ext-mykola.farion@here.com>

Align placeholder values in samples

---

auto-suggest-ios-swift/AutoSuggestApp.xcodeproj/project.pbxproj
geocoder-and-reverse-geocoder-ios-swift/GeocoderRevGeocoderApp.xcodeproj/project.pbxproj
here-positioning-ios-swift/HEREPositioningApp.xcodeproj/project.pbxproj
map-attribute-ios-swift/MapAttributeApp.xcodeproj/project.pbxproj
map-attribute-ios-swift/MapAttributeApp/SettingsViewController.swift
map-customization-ios-swift/MapCustomizationApp.xcodeproj/project.pbxproj
map-downloader-ios-swift/MapDownloaderApp.xcodeproj/project.pbxproj
map-gestures-ios-swift/MapGesturesApp.xcodeproj/project.pbxproj
map-gestures-ios-swift/MapGesturesApp/ViewController.swift
map-objects-ios-swift/MapObjectsApp.xcodeproj/project.pbxproj
map-raster-tile-ios-swift/MapRasterTilesApp.xcodeproj/project.pbxproj
map-rendering-ios-swift/MapEngineinitializationApp.xcodeproj/project.pbxproj
route-tta-ios-swift/RouteTTAApp.xcodeproj/project.pbxproj
routing-ios-swift/RoutingApp.xcodeproj/project.pbxproj
search-ios-swift/SearchApp.xcodeproj/project.pbxproj
search-ios-swift/SearchApp/Helper.swift
turn-by-turn-navigation-ios-swift/GuidanceApp.xcodeproj/project.pbxproj
turn-by-turn-navigation-ios-swift/GuidanceApp/MainViewController.swift

Signed-off-by: dashchak <ext-roman.dashchakivskyi@here.com>

Converted Swift projects to support Swift 5.0

---

geocoder-and-reverse-geocoder-ios-swift/GeocoderRevGeocoderApp/Base.lproj/Main.storyboard
geocoder-and-reverse-geocoder-ios-swift/GeocoderRevGeocoderApp/ViewController.swift

Align app with Objective-C and Android version.

---

geocoder-and-reverse-geocoder-ios-swift/GeocoderRevGeocoderApp/Base.lproj/Main.storyboard

Fix warning.

---

.ci/buildAll.sh
here-mobile-sdk-ui-kit-swift/GuideMeToHERE.xcodeproj/project.pbxproj
here-mobile-sdk-ui-kit-swift/Podfile.lock
here-mobile-sdk-ui-kit-swift/README.md

Signed-off-by: datasun <datasun@users.noreply.github.com>

ESD-918: Update pod, project settings & build script to enable MSDKUI app

---

routing-ios-swift/RoutingApp/Base.lproj/Main.storyboard
routing-ios-swift/RoutingApp/MapViewController.swift
routing-ios/RoutingApp/Base.lproj/Main.storyboard
routing-ios/RoutingApp/MainViewController.m

Show Environmental Zones on map

---

routing-ios-swift/RoutingApp/MapViewController.swift
routing-ios/RoutingApp/MainViewController.m

Add example how to add banned areas for routing.

---

.github/ISSUE_TEMPLATE/bug_report.md

Signed-off-by: Dashchakivskyi, Roman <ext-roman.dashchakivskyi@here.com>

Changed default assignee for new issue
